### ISSUE TITLE
Вопрос

### ISSUE THREAD

**Issue by sssergy** [Houzich/Convert-Addresses-To-Hash160-For-Brute-Force#1]
Привет!
Немного не понял, для чего разбивка на файлы по 256 записей?
Возможно ли сделать без разбивки и с сохранением в текстовый файл?
Что делать с адресами P2WPKH “bc1q” и P2TR “bc1p”?

**Comment by Houzich** [comment]
Разбивка не по 256 записей, а на 256 файлов. В каждый файл сохраняются hash160, в которых первый байт соответствует номеру файла. Первое, и так и так нужно будет разбивать на файлы, так как базы могут быть большими. Второе, это делается для ускорения поиска по "базам" в программах брута и др.. По первому байту hash160 определяется в какой базе(из какого файла) искать, что явно уменьшает диапазон. Сейчас поддерживаются адреса P2PKH “1” и P2WPKH “bc1q”

**Comment by Houzich** [comment]
> Привет! Немного не понял, для чего разбивка на файлы по 256 записей? Возможно ли сделать без разбивки и с сохранением в текстовый файл? Что делать с адресами P2WPKH “bc1q” и P2TR “bc1p”?

Разбивка не по 256 записей, а на 256 файлов. В каждый файл сохраняются hash160, в которых первый байт соответствует номеру файла. Первое, и так и так нужно будет разбивать на файлы, так как базы могут быть большими. Второе, это делается для ускорения поиска по "базам" в программах брута и др.. По первому байту hash160 определяется в какой базе(из какого файла) искать, что явно уменьшает диапазон. Сейчас поддерживаются адреса P2PKH “1” и P2WPKH “bc1q”

**Comment by Houzich** [comment]
> "По первому байту hash160 определяется в какой базе(из какого файла) искать, что явно уменьшает диапазон." Уменьшается диапазон чего именно? Да и для чего? Ведь неизвестно в каком месте кривой может этот адрес находиться. Причем совсем не важно какие биты идут в начале адреса.

Это программа для создания "баз" с которыми работает другая программа. Когда я выложу вторую, думаю будет понятно

**Comment by sssergy** [comment]
Благодарю за пояснение.
